name: License Checker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  licensed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Licensed
        uses: jonabc/setup-licensed@v1
        with:
          version: 2.x
      - name: Install dependencies
        run: dotnet restore **/ObjPropsDynamicSetter.sln
      - name: Run Licensed
        uses: jonabc/licensed-ci@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
