name: Mutation Tests

on:
  workflow_run:
    workflows: [Tests]
    branches: [main]
    types: [completed]

jobs:
  mutation-tests:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success' && github.repository == 'Molnix888/obj-props-dynamic-setter'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - name: Install Stryker
        run: dotnet tool install -g dotnet-stryker
      - name: Mutation Tests
        run: |
          cd **/test/*.Unit
          dotnet stryker -level Complete -ca perTestInIsolation -r "['dashboard']" --dashboard-api-key ${{ secrets.STRYKER_API_KEY }} --dashboard-project "github.com/Molnix888/obj-props-dynamic-setter" --dashboard-version ${GITHUB_REF##*/}
